FROM openjdk:16

COPY . /usr/src/myapp

WORKDIR /usr/src/myapp

RUN javac Main.java

CMD ["java", "Main"]


##################################################
# Docker Command
#
# docker build
# $ docker build -t my-java-app .
#
# docker run
# $ docker run -it --rm --name my-java-running-app my-java-app
#
##################################################